Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -149,348 +149,177 @@ jobs:
   scan-backend:
     docker:
       # Docker image here
-      - image: circleci/node:13.8.0
     steps:
       # Checkout code from git
-      - checkout
       # Restore from cache
-      - restore_cache:
-          keys: [backend-build]
       # Your job code here
-      - run:
-          name: Scan fronend dependencies
-          command: |
-            cd backend
-            npm install
-            npm audit --audit-level=critical || true
-            
+
   deploy-infrastructure:
     docker:
       # Docker image here that supports AWS CLI
-      - image: amazon/aws-cli
     steps:
       # Checkout code from git
-      - checkout
-      - run: yum -y install tar gzip
       - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
-              --tags project=udapeople \
-              --stack-name udapeople-backend-<< pipeline.parameters.workflow-id >> \
-              --parameter-overrides ID="<< pipeline.parameters.workflow-id >>" \
-              --tags project=udapeople 
-          no_output_timeout: 30m
-          
+              #--tags project=your-tag \
+              # --stack-name "your back-end stack name with workflow id" \
+              # --parameter-overrides ID="your workflow id"  
+              exit 1
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
-              --tags project=udapeople \
-              --stack-name udapeople-frontend-<< pipeline.parameters.workflow-id >> \
-              --parameter-overrides ID="<< pipeline.parameters.workflow-id >>" \
-              --tags project=udapeople
+              #--tags project=your-tag \
+              # --stack-name "your front-end stack name with workflow id" \
+              # --parameter-overrides ID="your workflow id"  
+              exit 1
       - run:
           name: Add back-end ip to ansible inventory
           command: |
             # Your code here
-            aws ec2 describe-instances \
-              --filters "Name=tag:project,Values=udapeople" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text >> .circleci/ansible/inventory.txt
-            cat .circleci/ansible/inventory.txt
-          no_output_timeout: 30m
-          
+            exit 1
       - persist_to_workspace:
-          root: .circleci/ansible
+          root: ~/
           paths:
-            - inventory.txt
-      - attach_workspace:
-          at: .circleci/ansible/
+            - project/.circleci/ansible/inventory.txt
       # Here's where you will add some code to rollback on failure      
-      - destroy_environment       
-
 
   configure-infrastructure:
     docker:
       # Docker image here that supports Ansible
-      - image: python:3.7-alpine3.11
     steps:
       # Checkout code from git
-      - checkout
       # Add ssh keys with fingerprint
-      - add_ssh_keys:
-          fingerprints: ["a6:ac:72:3c:e9:8b:eb:a6:9f:a4:fb:ec:d3:35:98:86"]
       # attach workspace
-      - attach_workspace:
-          at: ~/
       - run:
           name: Install dependencies
           command: |
             # Your code here
-            apk add --update ansible
-            # cat .circleci/ansible/inventory.txt
-            #exit 1
+            exit 1
       - run:
           name: Configure server
           command: |
             # Your code here
-            echo ENVIRONMENT=production > "backend/.env"
-            echo TYPEORM_CONNECTION=postgres >> "backend/.env"
-            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
-            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
-            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
-            echo NODE_ENV=production >> "backend/.env"
-            echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
-            echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
-            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
-            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
-            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"            
-            # cd .circleci/ansible
-            # pwd &&
-            # ls -la
-            # cat inventory
-            ansible-playbook \
-              -i .circleci/ansible/inventory.txt \
-              .circleci/ansible/configure-server.yml          
-            #exit 1
-      - run:
-          name: Install AWS CLI for rollback
-          when: on_fail
-          command: |
-            apk add --update py3-pip && pip3 install --upgrade pip && pip3 install awscli            
-      # Here's where you will add some code to rollback on failure  
-      - destroy_environment
+            exit 1
+      # Here's where you will add some code to rollback on failure      
 
   run-migrations:
     docker:
-      - image: circleci/node:13.8.0
+      # Docker image here that supports NodeJS
     steps:
-      - checkout
-      - restore_cache:
-          keys: [build-backend]      
+      # Checkout code from git
       - run:
           name: Run migrations
           command: |
-            cd backend
-            npm install
-            touch migration.txt
-            npm run migrations >> migration.txt
-            cat migration.txt
-          no_output_timeout: 30m
+            # Your code here
+            exit 1
       - run:
           name: Send migration results to memstash
           command: |
-            cd backend
-            cat migration.txt
-            result=0
-            if grep -q "has been executed successfully" migration.txt
-            then
-              result=1
-            fi
-            curl -H "Content-Type: text/plain" \
-            -H "token: migration_${CIRCLE_WORKFLOW_ID}" \
-            --request PUT \
-            --data ${result} https://api.memstash.io/values/migration
-            echo ${result}
-          no_output_timeout: 30m 
-      - run:
-          name: LogOnFail
-          when: on_fail
-          command: |
-            cat /home/circleci/.npm/_logs/*-debug.log
-            ls -la
-            cat backend/migration.txt          
-      - revert-migrations
-      - destroy_environment
-          
+            # Your code here
+            exit 1
+     # Here's where you will add some code to rollback on failure      
+
   deploy-frontend:
     docker:
       # Docker image here that supports AWS CLI
-      - image: amazon/aws-cli
     steps:
       # Checkout code from git
-      - checkout
       - run:
           name: Install dependencies
           command: |
-            curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
-            yum -y install nodejs
-            yum -y install tar gzip      
-      - attach_workspace:
-          at: ~/
+            # your code here
       - run:
           name: Get backend url
           command: |
             # your code here
-            BACKEND_IP=$(curl -H "token: IP-${CIRCLE_WORKFLOW_ID:0:9}" \
-                        --request GET https://api.memstash.io/values/IP)
             export API_URL="http://${BACKEND_IP}:3030"
-            echo API_URL="http://${BACKEND_IP}:3030" >> "frontend/.env"
             echo "${API_URL}"
       - run:
           name: Deploy frontend objects
           command: |
             # your code here
-            npm install webpack-dev-server -g
-            cd frontend
-            npm install
-            npm run build
-            aws s3 cp ./dist s3://udapeople-<< pipeline.parameters.workflow-id >> --recursive
       # Here's where you will add some code to rollback on failure      
-      - revert-migrations
-      - destroy_environment
-          
+                    
   deploy-backend:
     docker:
       # Docker image here that supports Ansible
-      - image: python:3.7-alpine3.11
     steps:
       # Checkout code from git
-      - checkout
       # Add ssh keys with fingerprint
-      - add_ssh_keys:
-          fingerprints: ["a6:ac:72:3c:e9:8b:eb:a6:9f:a4:fb:ec:d3:35:98:86"]     
-      - attach_workspace:
-          at: .circleci/ansible/
+      # attach workspace
       - run:
           name: Install dependencies
           command: |
             # your code here
-            apk add --update ansible
-            apk add --update tar gzip curl
-            apk add --update openssh-client
       - run:
           name: Deploy backend
           command: |
             # your code here
-            tar -C backend -czvf artifact.tar.gz .
-            ls -la           
-      - run:
-          name: Deploy backend 2
-          command: |
-            export ANSIBLE_HOST_KEY_CHECKING=False
-            ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i /tmp/.circleci/ansible/inventory.txt .circleci/ansible/deploy-backend.yml           
       # Here's where you will add some code to rollback on failure  
-      - revert-migrations      
-      - destroy_environment
-          
+
   smoke-test:
     docker:
       # Lightweight Docker image 
-      - image: python:3.7-alpine3.11      
     steps:
       # Checkout code from git
-      - checkout
       - run:
           name: Install dependencies
           command: |
             # your code here
-            apk add --update curl            
       - run:
           name: Get backend url
           command: |
             # your code here
-            export BACKEND_URL=$(sed -n 2p .circleci/ansible/inventory.txt)
       - run:
           name: Backend smoke test.
           command: |
             # your code here
-            if curl -s https://${BACKEND_URL}:3030/api/status
-            then
-            return 1
-            else
-            return 0
-            fi            
       - run:
           name: Frontend smoke test.
           command: |
             # your code here
-            URL="http://    << pipeline.parameters.workflow-id >>.s3-website-us-east-1.amazonaws.com"
-            echo $URL
-            if curl -s ${URL} | grep "Welcome"
-            then
-            return 1
-            else
-            return 0
-            fi
       # Here's where you will add some code to rollback on failure  
-      - destroy_environment
-      - revert-migrations      
+
   cloudfront-update:
     docker:
       # Docker image here that supports AWS CLI
-      - image: amazon/aws-cli
     steps:
       # Checkout code from git
-      - checkout
       - run:
           name: Install dependencies
           command: |
             # your code here
-            yum -y install tar gzip
       - run:
           name: Update cloudfront distribution
           command: |
             # your code here
-            export OldWorkflowID=$(aws cloudformation list-exports \
-            --query "Exports[?Name==\`WorkflowID\`].Value" \
-            --no-paginate --output text)
-            
-            export STACKS=$(aws cloudformation list-stacks \
-            --query "StackSummaries[*].StackName" \
-            --stack-status-filter CREATE_COMPLETE \
-            --no-paginate --output text)
-            
-            echo OldWorkflowID: "$OldWorkflowID"
-            echo STACKS: "$STACKS" 
-            aws cloudformation deploy \
-            --template-file /root/project/.circleci/files/cloudfront.yml \
-            --stack-name udapeople-cloudfront \
-            --parameter-overrides WorkflowID="<< pipeline.parameters.workflow-id >>" \
-            --tags project=udapeople
-            curl -H "Content-Type: text/plain" -H "token: OldWorkflowID-${CIRCLE_WORKFLOW_ID}" \
-            --request PUT \
-            --data "$OldWorkflowID" https://api.memstash.io/values/OldWorkflowID           
       # Here's where you will add some code to rollback on failure  
-      - revert-migrations
-      - destroy_environment
-          
-  cleanup:
+
+cleanup:
     docker:
       # Docker image here
-      - image: amazon/aws-cli
     steps:
-      # Checkout code from git 1
-      - checkout
+      # Checkout code from git
       - run:
           name: Get old stack workflow id
           command: |
-            OldWorkflowID=$(curl -H "token: OldWorkflowID-${CIRCLE_WORKFLOW_ID}" \
-            --request GET https://api.memstash.io/values/OldWorkflowID)
-            export STACKS=$(aws cloudformation list-stacks \
-            --query "StackSummaries[*].StackName" \
-            --stack-status-filter CREATE_COMPLETE \
-            --no-paginate --output text)
-            echo OldWorkflowID: "$OldWorkflowID"
-            echo STACKS: "$STACKS" 
+            # your code here
+            export OldWorkflowID="the id here"
+            export STACKS=[] #put the list of stacks here
       - run:
           name: Remove old stacks and files
           command: |
-            if [ ! -z $OldWorkflowID ]
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
             then
-              echo "I'm HERE !!!"
-              aws s3 rm s3://udapeople-${OldWorkflowID} --recursive
-              aws s3 rb s3://udapeople-${OldWorkflowID} --force
-              aws cloudformation delete-stack --stack-name backend-${OldWorkflowID}
-              aws cloudformation delete-stack --stack-name frontend-${OldWorkflowID}
-              echo "Stacks deleted succesfully"
-            else
-              echo "Fresh New Stacks"
+              # your code here
             fi
             
+
 workflows:
   default:
     jobs:
@@ -508,7 +337,7 @@ workflows:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
           filters:
             branches:
-              only: [master]
+              only: [test-feature-branch]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
       - run-migrations:
